apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-operator
  namespace: monitoring-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: vm-operator
  name: vm-operator
  namespace: monitoring-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: vm-operator
  template:
    metadata:
      labels:
        control-plane: vm-operator
    spec:
      containers:
      - args:
        - --enable-leader-election
        command:
        - manager
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: VM_ENABLEDPROMETHEUSCONVERTEROWNERREFERENCES
          value: "true"
        image: victoriametrics/operator:v0.29.0
        name: manager
        resources:
          limits:
            cpu: 400m
            memory: 2Gi
          requests:
            cpu: 80m
            memory: 256Mi
      serviceAccountName: vm-operator
      nodeSelector:
        node_type: worker
      terminationGracePeriodSeconds: 10
